# Generated by Django 5.0.6 on 2024-07-22 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('background_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_background_image', to='core.file')),
                ('icon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_icon', to='core.file')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
